CREATE DATABASE IF NOT EXISTS PMS;
USE PMS;

-- Users
CREATE TABLE IF NOT EXISTS Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  UserName VARCHAR(100) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  Role VARCHAR(50) NOT NULL
);

-- Vehicle
CREATE TABLE IF NOT EXISTS Vehicle (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Plate_Number VARCHAR(30) NOT NULL UNIQUE,
  Brand VARCHAR(100) NOT NULL,
  Model VARCHAR(100) NOT NULL,
  Year INT NOT NULL,
  Vehicle_Type VARCHAR(50) NOT NULL,
  Purchase_Price DECIMAL(12,2) NOT NULL,
  Status VARCHAR(30) NOT NULL,
  OwnerUserId INT NOT NULL,
  CONSTRAINT fk_vehicle_owner FOREIGN KEY (OwnerUserId) REFERENCES Users(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Customer
CREATE TABLE IF NOT EXISTS Customer (
  id INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  Email VARCHAR(150) NOT NULL,
  PhoneNumber VARCHAR(30) NOT NULL,
  CreatedAt DATETIME NOT NULL,
  Status VARCHAR(30) NOT NULL,
  OwnerUserId INT NOT NULL,
  CONSTRAINT fk_customer_owner FOREIGN KEY (OwnerUserId) REFERENCES Users(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Promotion
CREATE TABLE IF NOT EXISTS Promotion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(150) NOT NULL,
  Description TEXT NOT NULL,
  Discount_Type VARCHAR(50) NOT NULL,
  Discount_Value DECIMAL(12,2) NOT NULL,
  Start_Date DATE NOT NULL,
  End_Date DATE NOT NULL,
  Status VARCHAR(30) NOT NULL,
  OwnerUserId INT NOT NULL,
  CONSTRAINT fk_promo_owner FOREIGN KEY (OwnerUserId) REFERENCES Users(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Promotion_Vehicle (link table)
CREATE TABLE IF NOT EXISTS Promotion_Vehicle (
  id INT AUTO_INCREMENT PRIMARY KEY,
  PromotionId INT NOT NULL,
  VehicleId INT NOT NULL,
  Performance VARCHAR(200) NOT NULL,
  CreatedByUserId INT NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_promo_vehicle UNIQUE (PromotionId, VehicleId),
  CONSTRAINT fk_pv_promotion FOREIGN KEY (PromotionId) REFERENCES Promotion(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pv_vehicle FOREIGN KEY (VehicleId) REFERENCES Vehicle(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pv_creator FOREIGN KEY (CreatedByUserId) REFERENCES Users(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);


